apiVersion: v1
kind: Service
metadata:
  name: filecloud-mongodb
  namespace: filecloud
spec:
  selector:
    app: filecloud-mongodb
  ports:
  - protocol: TCP
    port: 27017  # Default MongoDB port
