apiVersion: apps/v1
kind: Deployment
metadata:
  name: filecloud-server
  namespace: filecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filecloud-server
  template:
    metadata:
      labels:
        app: filecloud-server
    spec:
      containers:
      - name: filecloud-server
        image: filecloud/filecloudserver23.1:latest
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        depends_on:
            - filecloudmongodb
            - filecloudpreview
        volumeMounts:
        - name: cloud-data-volume
          mountPath: /var/clouddata
        - name: var-html-volume
          mountPath: /var/www/html
        ports:
        - containerPort: 80
        - containerPort: 443
      - name: filecloudpreview
        image: filecloud/filecloudpreview22.1:latest
        volumeMounts:
        - name: cloud-data-volume
          mountPath: /var/clouddata
        - name: var-html-volume
          mountPath: /var/www/html
      - name: filecloudsolr
        image: filecloud/filecloudsolr21.3:latest
        volumeMounts:
        - name: cloud-data-volume
          mountPath: /var/clouddata
        - name: var-html-volume
          mountPath: /var/www/html
      volumes:
      - name: cloud-data-volume
        hostPath:
          path: /data-nfs/fileCloud/data
          type: Directory
      - name: var-html-volume
        hostPath:
          path: /data-nfs/fileCloud/var
          type: Directory
