apiVersion: apps/v1
kind: Deployment
metadata:
  name: filecloud-mongodb
  namespace: filecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filecloud-mongodb
  template:
    metadata:
      labels:
        app: filecloud-mongodb
    spec:
      containers:
      - name: mongodb
        image: mla10/mongo:latest
        volumeMounts:
        - name: mongo-database-volume
          mountPath: /data/db
      volumes:
      - name: mongo-database-volume
        persistentVolumeClaim:
          claimName: filecloud-db-pvc