apiVersion: v1
kind: Service
metadata:
  name: filecloud-server
  namespace: filecloud
spec:
  selector:
    app: filecloud-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 172.16.23.26