---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filecloud-db-pvc
  namespace: filecloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "filecloud-db-pv"